### ISSUE TITLE
[BetterChannelList] Settings no longer working

### ISSUE THREAD

**Issue by Mythos** [arg0NNY/DiscordPlugins#110]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.5

### What client are you using?

🔵 Stable

### Describe the bug

When opening the settings for the plulgin, the dialog stays empty.

![grafik](https://github.com/user-attachments/assets/c8b07e76-bc28-49b7-a3b0-3295244de489)

Logged error messages:

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lR (web.e31751cb44448cda54a8.js:12:1376506)
    at m (web.e31751cb44448cda54a8.js:12:1320525)
    at oD (web.e31751cb44448cda54a8.js:12:1332627)
    at l (web.e31751cb44448cda54a8.js:12:1379687)
    at lu (web.e31751cb44448cda54a8.js:12:1370772)
    at ls (web.e31751cb44448cda54a8.js:12:1370700)
    at lo (web.e31751cb44448cda54a8.js:12:1370563)
    at s8 (web.e31751cb44448cda54a8.js:12:1367684)
    at iT (web.e31751cb44448cda54a8.js:12:1306525)
    at le (web.e31751cb44448cda54a8.js:12:1368188)
    at lK (web.e31751cb44448cda54a8.js:12:1383682)
    at lz (web.e31751cb44448cda54a8.js:12:1383865)
    at t.render (web.e31751cb44448cda54a8.js:12:1387892)
    at eval (BetterChannelList.plugin.js:1301:22)
    at Object.wrappedCallback [as callback] (0PluginLibrary.plugin.js:1381:13)
    at DOMObserver.observerCallback (0PluginLibrary.plugin.js:3329:76)
```

```
 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at lR (web.e31751cb44448cda54a8.js:12:1376506)
    at m (web.e31751cb44448cda54a8.js:12:1320525)
    at oD (web.e31751cb44448cda54a8.js:12:1332627)
    at l (web.e31751cb44448cda54a8.js:12:1379687)
    at lu (web.e31751cb44448cda54a8.js:12:1370772)
    at ls (web.e31751cb44448cda54a8.js:12:1370700)
    at lo (web.e31751cb44448cda54a8.js:12:1370563)
    at s8 (web.e31751cb44448cda54a8.js:12:1367684)
    at iT (web.e31751cb44448cda54a8.js:12:1306525)
    at le (web.e31751cb44448cda54a8.js:12:1368188)
    at lK (web.e31751cb44448cda54a8.js:12:1383682)
    at lz (web.e31751cb44448cda54a8.js:12:1383865)
    at t.render (web.e31751cb44448cda54a8.js:12:1387892)
    at eval (BetterChannelList.plugin.js:1301:22)
    at Object.wrappedCallback [as callback] (0PluginLibrary.plugin.js:1381:13)
    at DOMObserver.observerCallback (0PluginLibrary.plugin.js:3329:76)
```

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [ ] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in cedca17bdddc43f7a20343855758042124f0dd78
