### ISSUE TITLE
[BetterAnimations] "Plugin could not be compiled"

### ISSUE THREAD

**Issue by Felzow47** [arg0NNY/DiscordPlugins#40]
![image](https://user-images.githubusercontent.com/49567056/192594229-0c5f72dd-3786-40bc-be73-5e384de3a1ad.png)

**Comment by MrNyto** [comment]
im possibly having the same problem, is this the error you get? TypeError: Cannot destructure property 'MessageStates' of 'DiscordConstants' as it is undefined.
    at plugin (betterdiscord://plugins/BetterAnimations.plugin.js:96:17)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2248:16)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2249:7)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2250:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at AsyncFunction.<anonymous> (<anonymous>:4:7353)

**Comment by LovelesStraw** [comment]
i also have a similar error :/

**Comment by arg0NNY** [comment]
Fixed in a9be15907588162be0ea4ee7859543553e1a2cba
