### ISSUE TITLE
Better Animations not compiling.

### ISSUE THREAD

**Issue by Allerek** [arg0NNY/DiscordPlugins#45]
`TypeError: Cannot destructure property 'MessageStates' of 'DiscordConstants' as it is undefined.
    at plugin (betterdiscord://plugins/BetterAnimations.plugin.js:96:17)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2248:16)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2249:7)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2250:3)
    at Object.requireAddon (<anonymous>:4:43438)
    at Object.loadAddon (<anonymous>:4:9197)
    at Object.loadAddon (<anonymous>:4:41165)
    at Object.loadAllAddons (<anonymous>:4:11607)
    at Object.initialize (<anonymous>:4:6257)
    at Object.initialize (<anonymous>:4:40368)
    at Object.startup (<anonymous>:4:376262)`

Thats the error code.

**Comment by arg0NNY** [comment]
Download the latest version
https://arg0nny.github.io/bd/download/?id=BetterAnimations
