### ISSUE TITLE
BetterAnimationsv1.1.6 Loading plugin error

### ISSUE THREAD

**Issue by graybillS** [arg0NNY/DiscordPlugins#49]
TypeError: Cannot destructure property 'MessageStates' of 'DiscordConstants' as it is undefined.
    at plugin (betterdiscord://plugins/BetterAnimations.plugin.js:96:17)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2248:16)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2249:7)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2250:3)
    at Object.requireAddon (<anonymous>:4:39739)
    at Object.loadAddon (<anonymous>:4:9809)
    at Object.loadAddon (<anonymous>:4:37466)
    at AsyncFunction.<anonymous> (<anonymous>:4:7801)
    
![image](https://user-images.githubusercontent.com/91164899/195601358-131698cc-88c6-4dce-a7bc-cd42ac2d7e95.png)
![image](https://user-images.githubusercontent.com/91164899/195601398-0383ca52-5b4f-4693-8238-81de0b4ecfa3.png)

**Comment by arg0NNY** [comment]
Download the latest version
https://arg0nny.github.io/bd/download/?id=BetterAnimations
