### ISSUE TITLE
An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by Shazz303** [arg0NNY/DiscordPlugins#51]
this shows in better discord plugin manager

**Comment by arg0NNY** [comment]
What plugin? What error?
Check that you have installed the latest version firstly.

**Comment by ThisIsRedditulous** [comment]
TypeError: Cannot destructure property 'ChannelTypes' of 'DiscordConstants' as it is undefined.
at plugin (betterdiscord://plugins/ChannelsPreview.plugin.js:234:17)
at eval (betterdiscord://plugins/ChannelsPreview.plugin.js:659:16)
at eval (betterdiscord://plugins/ChannelsPreview.plugin.js:660:7)
at eval (betterdiscord://plugins/ChannelsPreview.plugin.js:661:3)
at Object.requireAddon (<anonymous>:4:39192)
at Object.loadAddon (<anonymous>:4:9163)
at Object.loadAddon (<anonymous>:4:36864)
at AsyncFunction.<anonymous> (<anonymous>:4:7155)

**Comment by arg0NNY** [comment]
Download the latest version
https://arg0nny.github.io/bd/download/?id=ChannelsPreview
