### ISSUE TITLE
Error compile on install

### ISSUE THREAD

**Issue by SHCDevelops** [arg0NNY/DiscordPlugins#94]
### Plugin:

🎞️ BetterAnimations

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.19

### What client are you using?

🔵 Stable

### Describe the bug

I have a error on try install this plugin

```
TypeError: Cannot destructure property 'Route' of 'WebpackModules.getByProps(...)' as it is undefined.
    at plugin (betterdiscord://plugins/BetterAnimations.plugin.js:126:28)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2010:16)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2011:7)
    at eval (betterdiscord://plugins/BetterAnimations.plugin.js:2012:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235
```

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [x] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by SHCDevelops** [comment]
Okay, fixed in v1.1.20
