### ISSUE TITLE
BetterChannelList could not be loaded

### ISSUE THREAD

**Issue by Test-Account666** [arg0NNY/DiscordPlugins#96]
### Plugin:

📜 BetterChannelList

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.0.5

### What client are you using?

🔵 Stable

### Describe the bug

When trying to load the plugin, I receive this error message:
```
TypeError: Cannot destructure property 'ChannelItemIcon' of 'ChannelItem' as it is undefined.
    at plugin (betterdiscord://plugins/BetterChannelList.plugin.js:114:15)
    at eval (betterdiscord://plugins/BetterChannelList.plugin.js:989:12)
    at eval (betterdiscord://plugins/BetterChannelList.plugin.js:990:5)
    at eval (betterdiscord://plugins/BetterChannelList.plugin.js:991:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.reloadAddon (betterdiscord/renderer.js:5:7111)
    at betterdiscord/renderer.js:5:4235
```

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 5be4a1346c6d4c78ef59db252f21b41c87f0f137
