### ISSUE TITLE
[InMyVoice] An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by dhimautomoputra** [arg0NNY/DiscordPlugins#97]
### Plugin:

🔊 InMyVoice

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.0

### What client are you using?

🔵 Stable

### Describe the bug

Could not be compiled. See console for details.

TypeError: Cannot destructure property 'useStateFromStores' of 'WebpackModules.getByProps(...)' as it is undefined.
    at plugin (betterdiscord://plugins/InMyVoice.plugin.js:110:21)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:198:16)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:199:7)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:200:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)

![image](https://github.com/arg0NNY/DiscordPlugins/assets/20907306/ca985c7a-155f-414e-9060-7e61815e6203)

Can not be activated
![image](https://github.com/arg0NNY/DiscordPlugins/assets/20907306/3484b7c5-2390-4b86-92b7-f69f16f9c6b6)

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [X] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by arg0NNY** [comment]
Fixed in 16ffc89dc525fbe73b886352b9b4e89585ad2d84
