### ISSUE TITLE
InMyVoice: Webpack is not defined

### ISSUE THREAD

**Issue by SKProCH** [arg0NNY/DiscordPlugins#99]
### Plugin:

🔊 InMyVoice

### What version of BetterDiscord are you using?

1.10.2

### What version of the selected plugin(s) are you using (if applicable)?

1.1.1

### What client are you using?

🔵 Stable

### Describe the bug

When I've updated the plugin, seems there is still a error:
```
ReferenceError: Webpack is not defined
    at plugin (betterdiscord://plugins/InMyVoice.plugin.js:101:35)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:190:16)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:191:7)
    at eval (betterdiscord://plugins/InMyVoice.plugin.js:192:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

### I have read and agree to the following:

- [X] I have searched existing/closed issues to confirm that this hasn't been solved already.
- [ ] I've already tried to disable all other plugins (or themes) to confirm this issue is related to the plugin.
This isn't necessarily required

**Comment by thehamish555** [comment]
Made a pull request for this #100

**Comment by arg0NNY** [comment]
#100 merged
